on: [push, pull_request]

name: CI test and lint

jobs:
  check_test:
    name: Check and test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Run cargo check
        run: cargo check

      - name: Run cargo check no features
        run: cargo check --no-default-features

      - name: Run cargo test
        run: cargo test

  lints:
    name: Lints
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Run cargo fmt
        run: cargo fmt --all -- --check

      - name: Run cargo clippy
        run: cargo clippy --all-targets -- -D warnings

  check_test_aarch64:
    name: Check and test Linux arm 64bit
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Run cargo check on arm
        run: cargo check

      - name: Run cargo test on arm
        run: cargo test

  check_wasm32:
    name: Check wasm32
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-wasip1

      - name: Run cargo check on wasm32
        run: cargo check --target=wasm32-wasip1

  test_32bit:
    name: Test 32-bit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: i686-unknown-linux-gnu

      - name: Run cargo test on 32-bit
        run: cargo test target=i686-unknown-linux-gnu
